### ISSUE TITLE
Duplication Issue with Arcane Worktable recipes

### ISSUE THREAD

**Issue by FakoTheGreat** [Modbder/ThaumicBases#30] opened 2016-01-25 01:21 UTC
When crafting recipes in the Arcane Worktable, the items are not consumed for the craft.  It takes Vis from the wand and gives you the resulting item as appropriate, but you're able to continue pulling out more copies of the output item.  Shift + Clicking to pull out a stack instead drains the wand of relevant Vis and gives you as many copies as the current reserves in the wand would allow you to make, regardless of how many items are in the table to craft with.

Example, using salis mundus blocks:
![duplication issue](https://cloud.githubusercontent.com/assets/7228255/12540465/e2f161a4-c2c6-11e5-9e6f-9441412b7c0f.jpg)

This issue doesn't happen with crafting recipes from other Thaumcraft add ons, which is why I am reporting it here.

Relevant versions:
Minecraft 1.8.9
Forge 1715
Thaumcraft 5.1.4
Thaumic Bases 2.1.189-21

**Comment by Modbder** [comment] 2016-01-25 01:52
I just can't see the reason to why that would be happening - there is nothing special with the recipe registration:
https://github.com/Modbder/ThaumicBases/blob/1.8/java/tb/init/TBThaumonomicon.java#L138
And there is nothing special with the item itself:
https://github.com/Modbder/ThaumicBases/blob/1.8/java/tb/common/item/TBResource.java
That makes me believe that it must be a bug in TC itself, unless for some reason I now need to register the recipe in a different way, telling TC to not duplicate my items... yea, I do not see that being the case...
In any way it is a duplicate of #29 - that issue is left open for a reason :P

**Closed as completed by Modbder** 2016-01-25 01:52 UTC
Labels: duplicate
